spring:
  application:
    name: framework
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:server.p12
    key-store-password: keystore
    key-store-type: PKCS12
  compression:
    enabled: true
info:
  app:
    name: ${spring.application.name}
    port: ${server.port}
    version: @project.version@
    jdk: @java.version@
    cloud: @spring-cloud.version@
management:
  endpoints:
    web:
      base-path: /actuator
      cors:
        allowed-origins: '*'
        allowed-methods: '*'
#      exposure:
#        include: '*'
